# Generated by Django 5.0.6 on 2025-11-04 15:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('breed', models.CharField(blank=True, max_length=255, verbose_name='Cins')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
            ],
            options={
                'verbose_name': 'Quş növü',
                'verbose_name_plural': 'Quş növləri',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FarmLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('location_type', models.CharField(choices=[('incubator', 'İnkubator'), ('brooder', 'Yetişdirmə'), ('production', 'İstehsal'), ('feed', 'Yem anbarı'), ('processing', 'Ət emalı'), ('other', 'Digər')], default='other', max_length=20, verbose_name='Sahə tipi')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tutum (baş)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
            ],
            options={
                'verbose_name': 'Təsərrüfat sahəsi',
                'verbose_name_plural': 'Təsərrüfat sahələri',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('energy_kcal', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Enerji (kcal/kg)')),
                ('protein_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Zülal %')),
            ],
            options={
                'verbose_name': 'Yem növü',
                'verbose_name_plural': 'Yem növləri',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Partiya kodu')),
                ('origin', models.CharField(blank=True, max_length=255, verbose_name='Mənşə')),
                ('arrival_date', models.DateField(verbose_name='Gətirilmə tarixi')),
                ('initial_quantity', models.PositiveIntegerField(verbose_name='Başlanğıc say')),
                ('current_quantity', models.PositiveIntegerField(editable=False, help_text='Sistem əməliyyatları əsasında yenilənir', verbose_name='Cari say')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('sold', 'Satılıb'), ('disposed', 'Tələf olub'), ('archived', 'Arxiv')], default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='poultry.birdspecies', verbose_name='Quş növü')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='poultry.farmlocation', verbose_name='Cari sahə')),
            ],
            options={
                'verbose_name': 'Quş partiyası',
                'verbose_name_plural': 'Quş partiyaları',
                'ordering': ('-arrival_date', 'code'),
            },
        ),
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(verbose_name='Tarix')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdar (kg)')),
                ('note', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_logs', to='poultry.batch', verbose_name='Partiya')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_logs', to='poultry.farmlocation', verbose_name='Sahə')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_entries', to=settings.AUTH_USER_MODEL, verbose_name='Qeyd edən')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_logs', to='poultry.feedtype', verbose_name='Yem növü')),
            ],
            options={
                'verbose_name': 'Yemləmə qeydi',
                'verbose_name_plural': 'Yemləmə qeydləri',
                'ordering': ('-record_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='IncubationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incubator_section', models.CharField(max_length=100, verbose_name='İnkubator bölməsi')),
                ('egg_category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('mixed', 'Qarışıq')], default='A', max_length=10, verbose_name='Yumurta kateqoriyası')),
                ('eggs_set', models.PositiveIntegerField(verbose_name='Qoyulan yumurta sayı')),
                ('set_date', models.DateField(verbose_name='Yerləşdirmə tarixi')),
                ('expected_hatch_date', models.DateField(blank=True, null=True, verbose_name='Gözlənilən çıxış tarixi')),
                ('hatched_chicks', models.PositiveIntegerField(default=0, verbose_name='Çıxan cücələr')),
                ('hatch_date', models.DateField(blank=True, null=True, verbose_name='Faktiki çıxış tarixi')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incubations', to='poultry.batch', verbose_name='Bağlı partiya')),
            ],
            options={
                'verbose_name': 'İnkubasiya əməliyyatı',
                'verbose_name_plural': 'İnkubasiya əməliyyatları',
                'ordering': ('-set_date',),
            },
        ),
        migrations.CreateModel(
            name='MortalityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(verbose_name='Tarix')),
                ('count', models.PositiveIntegerField(verbose_name='Sayı')),
                ('mortality_type', models.CharField(choices=[('disease', 'Xəstəlik'), ('accident', 'Qəza'), ('culling', 'Seçmə (Cull)'), ('other', 'Digər')], default='other', max_length=20, verbose_name='Səbəb')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Ətraflı səbəb')),
                ('note', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_logs', to='poultry.batch', verbose_name='Partiya')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortality_entries', to=settings.AUTH_USER_MODEL, verbose_name='Qeyd edən')),
            ],
            options={
                'verbose_name': 'Tələfat qeydi',
                'verbose_name_plural': 'Tələfat qeydləri',
                'ordering': ('-record_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(verbose_name='Tarix')),
                ('eggs_total', models.PositiveIntegerField(verbose_name='Yumurta sayı')),
                ('category', models.CharField(choices=[('table', 'Süfrə yumurtası'), ('hatching', 'İnkubasiya yumurtası'), ('industrial', 'Sənaye yumurtası')], default='table', max_length=20, verbose_name='Kateqoriya')),
                ('note', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='poultry.batch', verbose_name='Partiya')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_logs', to='poultry.farmlocation', verbose_name='Saxlanma sahəsi')),
            ],
            options={
                'verbose_name': 'İstehsal qeydi',
                'verbose_name_plural': 'İstehsal qeydləri',
                'ordering': ('-record_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(verbose_name='Tarix')),
                ('item_type', models.CharField(choices=[('bird', 'Quş'), ('egg', 'Yumurta'), ('product', 'Məhsul')], max_length=20, verbose_name='Məhsul növü')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdar')),
                ('unit', models.CharField(default='ədəd', max_length=20, verbose_name='Ölçü vahidi')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Vahid qiymət')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Müştəri')),
                ('document_number', models.CharField(blank=True, max_length=255, verbose_name='Sənəd nömrəsi')),
                ('note', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='poultry.batch', verbose_name='Partiya')),
            ],
            options={
                'verbose_name': 'Satış qeydi',
                'verbose_name_plural': 'Satış qeydləri',
                'ordering': ('-record_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Tarix')),
                ('feed_used_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Yem (kg)')),
                ('eggs_collected', models.PositiveIntegerField(default=0, verbose_name='Toplanan yumurta')),
                ('mortality_count', models.PositiveIntegerField(default=0, verbose_name='Tələfat')),
                ('live_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Canlı çəki (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='poultry.batch', verbose_name='Partiya')),
            ],
            options={
                'verbose_name': 'Gündəlik göstərici',
                'verbose_name_plural': 'Gündəlik göstəricilər',
                'ordering': ('-date',),
                'unique_together': {('batch', 'date')},
            },
        ),
    ]
